spring.application.name=GS1_Java

# Configura��o do Banco de Dados H2 em modo arquivo (file mode) na raiz do projeto
spring.datasource.url=jdbc:h2:file:./data/base_lunar_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Atualiza o esquema do banco automaticamente com base nas classes Model
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Habilita o console do H2 no navegador (muito �til para testarmos se os dados est�o salvando)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console